version: '3'
services:

  node0:
    build: .
    container_name: node0
    command: python app.py
    networks:
      myapp:
        ipv4_address: 172.16.238.10

  node1:
    build: .
    container_name: node1
    command: python app.py

    networks:
      myapp:
        ipv4_address: 172.16.238.11

  node2:
    build: .
    container_name: node2
    command: python app.py
    networks:
      myapp:
        ipv4_address: 172.16.238.12

  node3:
    build: .
    container_name: node3
    command: python app.py
    networks:
      myapp:
        ipv4_address: 172.16.238.13

networks:
  myapp:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
