version: '3'
services:
  node0:
    build:
      context: .
    image: algo-network
    container_name: node0
    networks:
      myapp:
        ipv4_address: 172.16.238.10
    ports:
      - '8000'

  node1:
    build:
      context: .
    image: algo-network
    container_name: node1
    networks:
      myapp:
        ipv4_address: 172.16.238.11
    ports:
      - '8000'

  node2:
    build:
      context: .
    image: algo-network
    container_name: node2
    networks:
      myapp:
        ipv4_address: 172.16.238.12
    ports:
      - '8000'

  node3:
    build:
      context: .
    image: algo-network
    container_name: node3
    networks:
      myapp:
        ipv4_address: 172.16.238.13
    ports:
      - '8000'

networks:
  myapp:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
